###
GET http://localhost:3012/api/chanteurs

###
GET  http://localhost:3012/api/musiques

###
POST http://localhost:3012/api/chanteurs
content-type: application/json

{
    "data": {
        "nom": "Pagny",
        "prenom": "Florent",
        "dateDeNaissance": "1946-01-26"
    }
}

###
POST   http://localhost:3012/api/musiques
content-type: application/json

{
    "data": {
        "titre": "Savoir aimer",
        "lien_youTube": "https://www.youtube.com/watch?v=Q3Kvu6Kgp88",
        "{chanteur}": 6,
        "favoris": true,
        "dateDeSortie": "1950-03-18",
        "couleur_de_fond": "#134522"
    }
}

###
POST  http://localhost:3012/api/auth/local
content-type: application/json

{
    "identifier": "calanfive",
    "password": "Thomasi139!"
}